
server {
	# ----------| Listen on port 443 with SSL certificate |
	listen 443 ssl;
	listen [::]:443 ssl;
	
	# ----------| Protocol versions allowed (only v1.2 and v1.3) |
	ssl_protocols TLSv1.2 TLSv1.3;
	
	# ----------| Ciphers (criptography) |
	ssl_ciphers HIGH:!aNULL:!MD5;
	
	# ----------| Certificate path and keys |
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;
	
	# ----------| Server name |
	server_name ${DOMAIN_NAME};
	
	# ----------| Root dir for website files |
	root /var/www/html;
	index index.php index.html;
	
	# ----------| WordPress files location |
	location / {
		try_files $uri $uri/ /index.php?$args;
	}
	
	# ----------| File management PHP through PHP-FPM |
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000;  # WP container name
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}