# ------------------------------| DOCKER COMPOSE |

# ----------| Services |
services:

# ----------| NGINX |
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - ../.env

# ----------| WordPress + PHP-FPM |
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    # restart: always
    env_file:
      - ../.env

# ----------| MariaDB |
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - ../.env

# ----------| Volumes (data percistence) |
volumes:
  wordpress_files:
    name: wordpress_files
  mariadb_data:
    name: mariadb_data

# ----------| Internal network |
networks:
  inception_network:
    name: inception_network
    driver: bridge