[www]

# ----------| user/group without privilege for security |
user = nobody
group = nobody

# ----------| Listen to all interfaces on port 9000 |
listen = 0.0.0.0:9000

# ----------| Only accept conections from nginx (container named nginx) |
listen.allowed_clients = nginx

# ----------| Manage PHP processes by demand |
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

# ----------| Allow ".env" vars reach PHP |
clear_env = no